# 
FROM node:14 as development
WORKDIR /home/node/app
ENV NODE_ENV development
ENV PATH /home/node/app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . ./
CMD ["npm", "start"]
