version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: strahd
      POSTGRES_PASSWORD: dont_put_plaintext_passwords_here
      POSTGRES_DB: barovian_activity_map
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - './backend:/usr/src/app'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - './frontend:/home/node/app'
