# Generated by Django 3.1.5 on 2021-01-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barovian_activity_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Asset',
        ),
    ]
