# Generated by Django 3.1.5 on 2021-02-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barovian_activity_map', '0002_auto_20210128_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('x', models.IntegerField(default=False)),
                ('y', models.IntegerField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barovian_activity_map.eventtypes')),
            ],
        ),
    ]
